### ISSUE TITLE
Fix Failing test

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#101]
We moved listing carriers from show to index, so we need to update the tests to reflect that change.

Failing tests:
https://travis-ci.org/rubyforgood/babywearing

**Comment by pollygee** [comment]
@LizPrescott are you able to look at this?  If so please assign it to yourself, thanks!

**Comment by LizPrescott** [comment]
I will fix this. Sorry I missed it!

**Comment by pollygee** [comment]
No worries thanks!
