### ISSUE TITLE
FIX N+1 on the carriers#index

### ISSUE THREAD

**Issue by dixpac** [rubyforgood/babywearing#106]
When rendering `carriers#index` we have N+1 on this [line](https://github.com/rubyforgood/babywearing/blob/master/app/views/carriers/index.html.erb#L19).
For each row we are firing new DB query to fetch the location.

Expected:
Preload locations upfront using `included` on the `ActiveRecord::Relation`

**Comment by dixpac** [comment]
@LizPrescott would you be comfortable addressing this issue?

**Comment by LizPrescott** [comment]
Yep! Thanks for alerting me.
