### ISSUE TITLE
Add Statuses to Carriers

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#107]
For carriers, we need four separate status options
- `Available`
- `Disabled`
- `Sold`
- `Unavailable`

These statuses should be a dropdown on the carrier's page.  

We would also like a method on the carrier model called `available_for_checkout?` which will return false for all these status' except `Available`

**Comment by Rgaliant** [comment]
Hello, I am going to open a PR for this if that's alright.

**Comment by pollygee** [comment]
Hi @Rgaliant thanks so much for being so involved in our project!  Sorry this ticket is blocked, we have to decide how we want this implement the checkout process and the way we implement this will be dependent on what we decide there.  We have a meeting tomorrow to discuss this and we'll know more then.

Feel free to join our slack so you can join the conversation about the project.  The link is on our website www.rubyforgood.org (the # is a link to the invite).  We have a #babywearing channel there.  

After our meeting we'll have a bunch more ticket in that will be ready to be worked on.  Be sure to checkout the labels for "help wanted".  Thanks again, we're so grateful for your help!

**Comment by Rgaliant** [comment]
@pollygee thanks! I'd love to contribute a couple more PR's for hacktoberfest

**Comment by pollygee** [comment]
@Rgaliant we are unblocked here.  I made some edits in the ticket itself.
 I know you've taken on some other stuff, but you had done some work on this - do you want to be assigned to this issue too or should we open it up for someone else to pick up?

**Comment by pollygee** [comment]
@Rgaliant  you've got a lot you're working on at the moment :) So I'm going to to open this up for someone else to pickup.  Thanks for all you're doing!

**Comment by pollygee** [comment]
@ludamillion any interest in this issue?

**Comment by pollygee** [comment]
This ticket is up for grabs!

**Comment by ludamillion** [comment]
@pollygee Sorry just saw this now. Sure I'll take it.
