### ISSUE TITLE
Update /categories view to show Parent

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#109]
In `/categories`, the view is currently confusing as the Parent categories and subcategories are listed inline with each other. 

![image](https://user-images.githubusercontent.com/47750744/66719161-fe23c300-edb9-11e9-83b6-ebb8bf468b0d.png)

We need to change the `/categories` view so that its default view lists _only_ Parent categories.

When a Parent category is clicked, we should then display all associated sub-categories assigned to that Parent.

**Comment by mauricio-prl** [comment]
@abronkema Can I try to do it?
