### ISSUE TITLE
"Add Item" should link to /carriers/new

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#110]
The `Add Item` link in the nav bar should be updated to redirect to `carriers/new`

![image](https://user-images.githubusercontent.com/47750744/66719191-a3d73200-edba-11e9-8833-3396fab2a9ac.png)

**Comment by Nada1996** [comment]
@abronkema  can I start working on this?

**Comment by Nada1996** [comment]
Hi @abronkema , I created a PR #112 for this issue, can you please review it?
