### ISSUE TITLE
Remove Organization

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#111]
We currently have Organization, and we need to remove it.  It's been confusing, and for now we only have one organization.  We won't have more for a long time, so we don't want to overly complicate our MVP for the unknown in the future.  So going forward we want to build for only one org and want to remove what we have currently that uses it.

**Comment by DamirSvrtan** [comment]
@pollygee is this something you'll be picking up?

**Comment by pollygee** [comment]
@DamirSvrtan yep!  I assigned it to myself, I'm on it!!  Thanks.
