### ISSUE TITLE
Fee Type amount must be money

### ISSUE THREAD

**Issue by gabrielbaldao** [rubyforgood/babywearing#128]
When the user will create a new Fee Type, currently, he must write a amount value without dot, for example, to create a amount of $ 88.88 he must write 8888, in database this is created like a integer type, but to show this value, it will be showed as $ 88.00, maybe in the future this may bring problems.

![valor_novo_fee_type](https://user-images.githubusercontent.com/20587352/66781155-f55dea80-eea8-11e9-9348-549c733f723d.png)
![valor_fee_type_salvo](https://user-images.githubusercontent.com/20587352/66781165-f7c04480-eea8-11e9-8127-a456fb3fb07b.png)

Solution,Maybe we can change your type in database to  [money type](https://www.postgresql.org/docs/9.1/datatype-money.html) and not have change the value in view.

**Comment by JuarezLustosa** [comment]
@gabrielbaldao You're alright, should this in decimal on the database. I can fix that
