### ISSUE TITLE
Need styling fix on upload carrier photo

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#146]
**Describe the bug**
When you add a new carrier at /carrier/new the "Browse" button needs styling, it doesn't fit inside the Photo box.   
![Babywearing](https://user-images.githubusercontent.com/10904005/66964654-3f7bd300-f045-11e9-8eaf-bd16d620dfae.jpg)

**Comment by Rgaliant** [comment]
I can try this one, I'll open up a PR tonight

**Comment by DamirSvrtan** [comment]
> I can try this one, I'll open up a PR tonight

Hi @Rgaliant, thanks for volunteering however seems like there's already a Pull Request in place: https://github.com/rubyforgood/babywearing/pull/147

**Comment by Rgaliant** [comment]
darn beat me to it
