### ISSUE TITLE
Carrier Images - Correct/Standardize Sizing

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#150]
**Describe the bug**
When navigating to `/carriers`, the placeholder images (see #59 ) appear much larger than photo uploads.

**To Reproduce**
1. Create user or log in
2. Click on 'Carriers' or navigate to `localhost:3000/carriers`
3. Images should load.

**Expected behavior**
The item containers should be the same size, and the images should also size up/down to be uniform in size. 

**Screenshots**

![image](https://user-images.githubusercontent.com/47750744/67018268-fbcaad00-f0c8-11e9-8937-b61bcb9e4a05.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context**
The styling/layout should be tested cross-browser as well. At a minimum, the expected layout should persist in Chrome, Firefox and Edge.

**Comment by Rgaliant** [comment]
just opened a PR to try and solve this 👍

**Comment by abronkema** [comment]
Thanks @Rgaliant ! I've gone ahead and assigned this to you.
