### ISSUE TITLE
[Nav Bar] Create "View Members" link for Admins/Volunteers

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#152]
In the top nav bar, we need to add a new link/icon/text called "View Members".

- Select an icon that fits the current theme (Bootstrap Admin SB 2), or you can use one that's tested, such as [Octicons](https://octicons.github.com/)
- Text should read "View Members"
- Icon and text should mirror other nav icon links/elements in alignment/sizing.
- This element should appear at the end of the nav bar and only be visible to authenticated users with an assigned role of Admin or Volunteer.
- This will link to a user list to be added in an upcoming issue.

![image](https://user-images.githubusercontent.com/47750744/67026307-7e596980-f0d5-11e9-9f61-a2a5e5fa66f9.png)

**Comment by Rgaliant** [comment]
I can tackle this one this evening!
