### ISSUE TITLE
Create Member List Table/View

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#153]
We need a page with a table added that lists all registered users and allows the option to edit their user role (Admin, Volunteer, Member) and a button to link to that user's profile page to edit their information.

- This page should only be accessible to authenticated users with an assigned role of Admin or Volunteer.
- Column 1 should be titled `Username` and list their usernames with the toggle option to reverse the sort
- Column 2 should be titled `First Name` and list their first name with the toggle options to sort ascending or descending
- Column 3 should be titled `Last Name` and list their last name alphabetically with the toggle options to sort ascending or descending. This column should be the default sort (alphabetically)
- Column 4 should be titled `User Role` and show a drop-down selection with their assigned role. This should _**only be editable by authenticated Admins**_ but should be viewable by Volunteers.
- Column 5 should be titled `Edit Profile` and each row should have a button link to that user's profile page. Authenticated Admins and Volunteers are allowed to edit User profile pages.

*** Search user functionality will be added in a later ticket

![User List Page](https://user-images.githubusercontent.com/47750744/67027679-faed4780-f0d7-11e9-9801-7818c80a264a.png)

Additional Requirement:
- In user `/edit` page, at the very bottom, a dropdown should be visible for Admins and Volunteers to `activate` or `deactivate` a user. 
- See #157 - `deactivated_at` will NOT delete the user. 
- `deactivated_at` should log a `datetime`

**Comment by Rgaliant** [comment]
Hey Anthony, I can take this one too

**Comment by pollygee** [comment]
@Rgaliant one important note.  We currently have 4 roles in rolify.  The roles are user, admin, volunteer and member.  User is kinda redundant, so we don't want to display that in this dropdown.  We'd want admin, volunteer, member, and disabled(which we currently don't have).  Maybe we could rename user to disabled?  That or we can remove user and add disabled.  

Also we don't have a username - so maybe that should be email @abronkema  what do you think?

**Comment by abronkema** [comment]
@pollygee @Rgaliant - correct, let's use email in place of username here.

**Comment by DamirSvrtan** [comment]
@pollygee does it make sense to open an issue ticket that explains what needs to be changed with user roles? Let's remove the redundant 'user' and add the 'disabled' one.

Let me know if you wanna create the issue or you want me to do that. If you have any documentation on that send it my way please!

**Comment by pollygee** [comment]
@DamirSvrtan I can do that, I don't want it to interfere with what @Rgaliant is doing here and cause some merge conflicts though.  I guess @Rgaliant if you want to wait to do this till we get that resolved then you can have that change?

**Comment by DamirSvrtan** [comment]
@pollygee I think @Rgaliant can continue on work with this as in this PR the roles should not be hardcoded, but the list should just be prefilled by doing `Role.all`.

**Comment by DamirSvrtan** [comment]
@pollygee this got me thinking, is 'disabled' really a role we wanna have? That does not sound like a role, but rather an extra attribute on the user model. What are your thoughts? (we can discuss this more in the issue you're opening).

**Comment by Rgaliant** [comment]
@abronkema by user profile page do we mean the user edit page?

**Comment by abronkema** [comment]
> @abronkema by user profile page do we mean the user edit page?

@Rgaliant yep! Edited text for clarification.
