### ISSUE TITLE
Update user roles

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#157]
**Is your feature request related to a problem? Please describe.**
We currently have 4 roles but one of them is redundant, and we need an additional one.

**Describe the solution you'd like**
We are using rolify gem in our app to handle the roles.  We have 4 roles currently, `user`, `member`, `volunteer`, and `admin`.

- [ ] Delete `user`
- [ ] Add a `datetime` column to `User` for `deactivated_at`

We will be left with 3 roles: `member`, `volunteer`, `admin`.

We will track `deactivated_at` history as a datetime for admin purposes.

Admins/Volunteers will be able to Deactivate a member via a dropdown in #159

I see the roles in the rails console:
```Role Load (0.8ms)  SELECT "roles".* FROM "roles"
[#<Role:0x00007ff71173df60
  id: 1,
  name: "admin",
  resource_type: nil,
  resource_id: nil,
  created_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00,
  updated_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00>,
 #<Role:0x00007ff71173ddd0
  id: 2,
  name: "volunteer",
  resource_type: nil,
  resource_id: nil,
  created_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00,
  updated_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00>,
 #<Role:0x00007ff71173dbf0
  id: 3,
  name: "member",
  resource_type: nil,
  resource_id: nil,
  created_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00,
  updated_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00>,
 #<Role:0x00007ff71173d8d0
  id: 4,
  name: "user",
  resource_type: nil,
  resource_id: nil,
  created_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00,
  updated_at: Wed, 09 Oct 2019 21:02:20 UTC +00:00>]

**Comment by pollygee** [comment]
@DamirSvrtan does that make sense? @rgaliant do you want to take this issue or let someone else pick it up?

**Comment by pollygee** [comment]
@DamirSvrtan I think we wanted a way to differentiate between a member who is active and inactive without loosing their history in case they reactivate.  Do you think it's better we don't do this as a role?

**Comment by abronkema** [comment]
@pollygee @DamirSvrtan - my thought on disabled as a role was sort of a
“what if they need to prohibit someone from reactivating membership (maybe
non-payment, fraud, etc)”. If there’s an easier way to accomplish it
without a defined role (but easily visible to Volunteers), great!

This (Disabled) wasn’t a request from the stakeholder. Just a thought as I
compared some membership management options in other apps.

**Comment by Rgaliant** [comment]
with rolify do we just need to delete the role from the database with id 4?

**Comment by dixpac** [comment]
My 2 cents on this topic:
When I think about wether user is active or deactivate I immediately think about some kind of status or flag column on the user, not the role itself. 

Thinking about `active -> deactivate -> active` use-case, if in the future we want to "deactivate" other roles for example `volunteer` we wouldn't know what was their "old" role when `activation` happens again.

Also, re retaining history, do we want to track when user deactivated, so we can purge them lets say after 3 months of?

**Comment by DamirSvrtan** [comment]
Seems like @dixpac and I are on the same page - `deactivated` or `disabled` is not a role - we'd rather want that as a separate column such as `deactivated_at`.

**Comment by pollygee** [comment]
@dixpac I like having a history of deactive, it would also allow an admin to have extra information.  I can imagine a situation where they might want to know how long a member has been deactive for.

What do you think @abronkema can we put in a separate ticket to add a boolean `active` on the user table, default to true.  We could add a toggle to /users page that the admin sees, and they could set someone to active or deactive?

**Comment by dixpac** [comment]
Actually I like @DamirSvrtan idea even more. We can have `deactivated_at`(datetime) column, if it is empty then `User` is active, else it is `deactive` and we have information when `deactivation` happened

**Comment by pollygee** [comment]
Ok so we want to do two things - 
1) delete `user`
2) add a column to User `deactivated_at` datetime column
3) display a dropdown on the user page that the admin so that the admin could change a user to deactive?

We could also down the line have some logic that would deactivate an account automatically if the dues weren't paid things like that, but an admin should be able to do it manually I think..  What do ya'll think?

**Comment by abronkema** [comment]
@pollygee @DamirSvrtan @dixpac @Rgaliant - I've updated the approach in the ticket to match the decision made here. I'll also update #159 or create a new ticket to update the dropdown in the User list view.
