### ISSUE TITLE
Merge Cart and Loan into single model object

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#165]
- [ ] Combine the `Cart` and `Loan` objects into a single model object named `Loan`.  

- [ ] The new `Loan`  model object should have a reference to the member making the loan.  

- [ ] The new `Loan` model object should have a property for `returned_at`, which will be set when a loan is returned.

- [ ] The new `Loan` object should have two different volunteer associations, one for the volunteer who checks it in, one for the volunteer who checks it out.

- [ ] The `Loan` object's status should be modified by `checkout` and `checkin` methods that encapsulate the desired behavior.  `checkout` should take as parameters the volunteer who is checking it in and the due date (nil implies default), `checkin` should take as parameter the volunteer who is checking the object in.

**Comment by pollygee** [comment]
@valeriecodes are you interested in this one?

**Comment by valeriecodes** [comment]
I'll take it, thanks @pollygee and @abronkema !

**Comment by valeriecodes** [comment]
Couple questions:

- What's the default due date?
- Should this also include code to migrate existing `Cart`s into the `Loan` data model? Or will the table just be dropped?
- Should the member who the item is checked out to also be passed to the `checkout` method?
- Are loans created before the checkout method is called on them (presumably without due dates or volunteers?) If not, should the checkout method create them? I think it might make most sense to not have a `checkout` method, but to require the presence of a checkout volunteer and set the due date according to the specified logic on create. Does that sound reasonable?

**Comment by valeriecodes** [comment]
Opened a PR, but I can tweak/finalize based on your responses to the above questions: https://github.com/rubyforgood/babywearing/pull/179

**Comment by dixpac** [comment]
@valeriecodes  I think I can answer first two quesitons. @abronkema  when you have some free time can you unblock @valeriecodes?

> What's the default due date?

I think default due date should be `now + default_loan_length_days` from the `Carrier`

> Should this also include code to migrate existing Carts into the Loan data model? Or will the table just be dropped?

We can just drop the `Cart` since we don't have any users using the app, still in the "building" phase.

**Comment by pollygee** [comment]
Sorry for the delay, I missed this. 

> Should the member who the item is checked out to also be passed to the checkout method?
Yes, I think you're right we'd need to know that too.

> Are loans created before the checkout method is called on them (presumably without due dates or volunteers?) If not, should the checkout method create them? I think it might make most sense to not have a checkout method, but to require the presence of a checkout volunteer and set the due date according to the specified logic on create. Does that sound reasonable?

I'm not sure....I didn't think a loan was created until the checkout method.  I think we need a checkout method because we want to look at historic data on a carrier and on a member.  WE also have different ways a carrier can be checked out (@dixpac is working on a second workflow for carrier checkout).  @abronkema what do you think?

We're really aiming for something basic here, so we can iterate on that.  We are hoping to get something in front of  MAB soon so we can get feedback and improve upon our first pass.

**Comment by abronkema** [comment]
@pollygee @valeriecodes - as long as we can support some way to reserve the item and check it out only if the requisite conditions are true: 
- member is an active member
- member has signed requisite agreements
- member does not currently have item(s) checked out that would exceed the carrier limit defined by their membership type

Does that make sense? Totally up to you guys on how to best implement that, but the solution needs to support these checks and the ability to warn the volunteer that they should not check out that item for any of the aforementioned reasons.

**Comment by pollygee** [comment]
I agree with your @abronkema  but I think that's all out of the scope of this ticket.  I think this starts to tread into the issues #166 and #167 

I think we've got kinda stuck here, and most important is just that we get ourselves to a place where we can get moving again.  @dixpac has a spike that works on that checkout functionality so maybe we don't even really need this solved here, maybe we can just work with what you've got so far @valeriecodes.  What do you think @dino?  I don't want you to be blocked waiting for this, would you be able to  move forward from what @valeriecodes has here if we were to merge it?

**Comment by dixpac** [comment]
@pollygee  I agree...I can make the basic MVP that works then we can go from there...just so we can show project stakeholders something
