### ISSUE TITLE
Add "Watch List" functionality to Carrier page

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#166]
- [ ] Members should be able to add carriers to a 'watch list' of carriers that they are interested in.  (This might need to be renamed.)   This should create a Loan object with no volunteers or due date associated with it.  

- [ ] This should be implemented as an action that creates the Loan and then redirects to the show page for the carrier if it succeeds.

- [ ] Members must have signed the appropriate disclosures to check out items;  if a member has not signed the required disclosures, they should be redirected to an information page for that.

**Comment by pollygee** [comment]
@valeriecodes or this one?

**Comment by valeriecodes** [comment]
I can do this next, but I probably won't get to it until tomorrow or the next day.

**Comment by pollygee** [comment]
@valeriecodes are you still planning to take this issue?

**Comment by valeriecodes** [comment]
Yes, sorry for delay, I can do it this weekend.

**Comment by pollygee** [comment]
I'm going to close this issue for now, Steph reports that this isn't the best use of our time at this point we have other more pressing needs.
