### ISSUE TITLE
Allow Volunteers/Admins to Checkout Carriers to Members

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#167]
- [ ] When a volunteer looks at a detail page for a carrier, they should see a list of members who are interested in checking it out (who have a Loan object that has no checkout information - see Watch list issue #166 )

- [ ] There should be a checkout button on each user in that list.  When the volunteer clicks on that button, they should go to a separate action that confirms the volunteer wants to check out the Carrier to the member.  It should also allow the volunteer to set a due date.

- [ ] If the member already has too many items checked out for their membership type, they should receive an error with explanatory text instead

**Comment by pollygee** [comment]
I think this one is blocked by #166 .  We need to have the list of members interested to be working in order to work on this.

**Comment by pollygee** [comment]
I'm going to close this issue for now, Steph reports that this isn't the best use of our time at this point we have other more pressing needs.
