### ISSUE TITLE
Move "Invalid Email or Password" error messages on Log In page

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#169]
When entering an invalid email or password on the Log In page, the text "Invalid Email or password" is displayed in the upper left. Please make the following adjustments:

- [ ] Change text from "Invalid Email or password" to "Invalid Email/Password"
- [ ] Error text should be red (color value is up to your discretion, should be vivid on the background)
- [ ] Increase error text size by ~25%
- [ ] Position the error text to be directly above the Log In component (see screenshot)

![image](https://user-images.githubusercontent.com/47750744/67401019-82c1ce80-f57c-11e9-859b-bc66626a0874.png)

**Comment by ahmedash95** [comment]
I'm taking this one :)

**Comment by abronkema** [comment]
Thanks @ahmedash95 ! I've assigned it to you

**Comment by ahmedash95** [comment]
Hello @abronkema. I made the PR. also, moving the position of the error message to the top of the login component would add more complexity to the project because you share the error module among the entire project so I hope the current implementation works for you.
