### ISSUE TITLE
Send Email on Due Date

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#172]
See #171 

- [ ] The system must send an email to the member's associated email address (based on the member who signed the item out) with a due date notification.

> Subject: Carrier Return Is Now Due

> "Dear <`first name`>,
>
> This is a reminder that your <`checked out carrier name`> is due back to <`current_location`> today.
>
>Thanks,
>MidAtlantic Babywearing

- [ ] This should be encapsulated in a job that is run daily.

**Comment by luchiago** [comment]
Is this issue still needs help?

**Comment by pollygee** [comment]
Hi!  Thanks so much. I’m actually working on the other mailers so I’ll prob just include this one too. I’ll fix the labels
