### ISSUE TITLE
only admins should be able to create/update/delete certain domain objects.

### ISSUE THREAD

**Issue by corprew** [rubyforgood/babywearing#174]
**Describe the bug**
Only admins should be able to create, edit, update, and delete the following objects:
* `MembershipType`
* `Category`
* `FeeType`
* `Location`
* `Agreement`

**To Reproduce**
1.  log out & go to website.  Log in as a standard member.
2. load the membership type controller.
3. create a new membership type.
4. observe success message
[repeat for other domain objects]

**Expected behavior**
Non-admin user should be prevented from creating, editing, or updating new objects of these types.

**Screenshots**
![image](https://user-images.githubusercontent.com/56199/67410576-2907d700-f571-11e9-888c-5c31921262f4.png)

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
**Additional context**

Note that we use the Pundit gem -- https://github.com/varvet/pundit -- for authorization and the Rolify gem for roles -- https://github.com/RolifyCommunity/rolify -- and the solution should use these gems' functionality.

**Comment by mauricio-prl** [comment]
Can I try this one?

**Comment by pollygee** [comment]
Thanks @m-pereira we appreciate all the help you're giving us!  I'm going to send you an invite to be a collaborator, if you want so you can self assign when you want to work on something!  Hopefully you'll stick around for a while!  😉

**Comment by mauricio-prl** [comment]
@pollygee It will be a pleasure
