### ISSUE TITLE
Restyle sign-up page using sb-admin-2

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#184]
In #141 , @ludamillion restyled the login page and we should take the opportunity to update our `/users/sign_up` page as well.

**Comment by pollygee** [comment]
@ludamillion are you still planning to work on this issue?

**Comment by ludamillion** [comment]
@pollygee I can but if there is someone else who wants to that's fine too. My work on the sign in page should be a pretty straightforward template for the work required. 

I don't have a ton of bandwidth right now as my family and I are preparing for the rapidly approaching arrival of our third child. 😄 but also 😱

**Comment by pollygee** [comment]
Nope!! Nobody else.  It had just been a few weeks so I was just touching base and checking if you still would be able to work on it or if I needed to try to find someone else to help!  Thanks 😺 No rush, just keep in touch.  

Congrats!!  That's so exciting.  I see lots of babywearing in your future!

Also feel free to recruit friends/colleagues to help us out!!  🤣
