### ISSUE TITLE
Need styling for /users

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#185]
/users has a table of users and their info, but it's tough to read.  We need some styling to make the table more readable and to match the other pages in our app.

![Babywearing](https://user-images.githubusercontent.com/10904005/67619132-d5da9200-f7c5-11e9-8fd7-dccd3cb9a2bb.jpg)

**Comment by dixpac** [comment]
@Rgaliant  is already "attacking" this in his PR #159

**Comment by pollygee** [comment]
Ah great thanks @dixpac I'll close this one!
