### ISSUE TITLE
Fix "Browse" button when creating a carrier

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#211]
Click "Add item" in the banner.
At the bottom of the page there is the option to add a photo, and the "browse" button is cut off.

We need to fix the styling so the whole button shows so it will look better.

![Babywearing](https://user-images.githubusercontent.com/10904005/68474534-a11e0000-01f3-11ea-8996-b216d3cec416.jpg)

**Comment by m-pereira** [comment]
I'll take a look on this
