### ISSUE TITLE
Fix rubocop violations

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#216]
We have over 200 rubocop violations.  We have created a TODO file with all the violations.  https://github.com/rubyforgood/babywearing/blob/master/.rubocop_todo.yml

In order to address some of these isuess, delete the lines of the TODO file you want to fix and run rubocop.  This will reveal the errors.  You can then fix them and run rubocop again.

Do not use the word fix or resolve in your PR so that it doesn't close this issue, as we will have lots of PRs associated with this issue until all the violations are corrected.

**Comment by mauricio-prl** [comment]
I want to work with this one.

**Comment by pollygee** [comment]
Great @m-pereira!  There are so many errors, we don't want to wait to merge fixed until they're all fixed.  So please follow the directions above and make a PR when you're done working for the day or whatever, that will allow others to work on it.  Then when you're ready to come back you can just make another PR.  It will probably take us a while to get through all these.

**Comment by mauricio-prl** [comment]
So I'm gonna work with this one: ```- 'spec/models/user_spec.rb'```

**Comment by DouglasLutz** [comment]
Can I work on some errors?

**Comment by mauricio-prl** [comment]
@DouglasLutz which are you working on?

**Comment by DouglasLutz** [comment]
> @DouglasLutz which are you working on?

I can work on `- 'spec/policies/fee_type_policy_spec.rb'` and `- 'spec/policies/user_policy_spec.rb'`

**Comment by mauricio-prl** [comment]
Ok, so I'm going to work on the other three:
- [x] ```'spec/policies/loan_policy_spec.rb'```
- [x]  ```'spec/policies/location_policy_spec.rb'```
- [x]  ```'spec/policies/membership_type_policy_spec.rb'```

**Comment by pollygee** [comment]
FYI @m-pereira @DouglasLutz @mark100net will be working on this today so if there are any particular files you're working on, please comment here.  He will be working on knocking out a bunch of these code violations today so I want to be sure he has the room to do that.  Thanks so much!
