### ISSUE TITLE
Inventory Page Search and Filter

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#22]
When viewing the inventory page (#21), a search bar should populate at the top, along with filter options.

- Users should be able to enter text into search input and view matching results based on:
-- Name
-- Manufacturer
-- Model

- Users should be able to filter by:
-- Location
-- Status
-- Category

Dependencies: #21 #19

**Comment by Aliciawyse** [comment]
I'm gonna give this a shot this week!

**Comment by abronkema** [comment]
@Aliciawyse - do you think you'll have time to work on this? If not, we have some folks who can take it and we'll have more inventory page work in the future!

**Comment by pollygee** [comment]
We need help to resolve this issue.  The work was started by Alicia worked on this but didn't finish, the progress she made is in a PR above.
