### ISSUE TITLE
Style all actions into buttons

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#221]
On the following pages, add styling to the "Edit", "Destroy", "Delete" buttons.

### `/carrer/#`
![image](https://user-images.githubusercontent.com/47750744/69060242-0c7e8380-09e5-11ea-8d73-8f01c2869f06.png)

### `/categories`
![image](https://user-images.githubusercontent.com/47750744/69060414-4f405b80-09e5-11ea-85b1-38666c9036ba.png)

### `/categories/#`
![image](https://user-images.githubusercontent.com/47750744/69060478-68490c80-09e5-11ea-819c-f156e360d9c1.png)

### `/locations`
![image](https://user-images.githubusercontent.com/47750744/69060516-75fe9200-09e5-11ea-8dc6-e60669b0f5d7.png)

### `/agreements`
![image](https://user-images.githubusercontent.com/47750744/69060558-86167180-09e5-11ea-8359-e1d28dbdb95f.png)

### `/agreements/1` and `/agreements/2`
![image](https://user-images.githubusercontent.com/47750744/69060593-9af30500-09e5-11ea-9ac2-f18792499677.png)

### `/fee_types`
![image](https://user-images.githubusercontent.com/47750744/69060634-ad6d3e80-09e5-11ea-8abc-52e4aa6e6b0f.png)

### `/fee_types/#`
![image](https://user-images.githubusercontent.com/47750744/69060667-bb22c400-09e5-11ea-8db4-323755231001.png)

### `/membership_types/new`
![image](https://user-images.githubusercontent.com/47750744/69060712-d1308480-09e5-11ea-8fbc-d341ee4b31e3.png)

**Comment by DouglasLutz** [comment]
Can I work on this?

**Comment by abronkema** [comment]
@DouglasLutz - definitely! Thank you! I've assigned it to you now - please let us know if you have any questions.

**Comment by DouglasLutz** [comment]
Hey @abronkema, I saw that there are other pages that also don't have buttons, such as categories creation. What do you think about changing the other ones too? I can open another PR for those
