### ISSUE TITLE
Admin Show All Checked Out Items

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#24]
While logged in as Admin, allow user to quickly get to a table showing all items in that organization, with the ability to filter the view by status. 

Table should show the following for each item in a 5-column layout:
- User item is checked-out to (Workflow not yet implemented)
- Item ID (clickable link to item's CRUD page (#7 ))
- Item Name (clickable link to item's CRUD page (#7 ))
- Item Location
- Item Status

**Comment by abronkema** [comment]
The data required to define `User item is checked-out` to will be added in column 1 once that workflow is complete.

**Comment by LizPrescott** [comment]
I got this one!
