### ISSUE TITLE
All Fees Should Be In Dollars, Not Cents

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#254]
in `/membership_types` and on creating a new membership type `/membership_types/new`, the fees listed should be in dollars and cents, where it is currently just listed in cents.

You can see this appropriately formatted in `/fee_types`

![image](https://user-images.githubusercontent.com/47750744/72228416-56fb2700-3574-11ea-8e65-826b6a7ac18c.png)

![image](https://user-images.githubusercontent.com/47750744/72228423-624e5280-3574-11ea-8948-d1cf954ce484.png)

**Comment by mark100net** [comment]
I suggest we use the `money-rails` gem and implement on this and any other existing monetary fields.

**Comment by sarslanoglu** [comment]
@abronkema @pollygee I can work on this one

**Comment by pollygee** [comment]
Awesome thanks @sarslanoglu welcome back!!

**Comment by sarslanoglu** [comment]
@mark100net Thanks to you I learned a really good gem today. Cheers!
