### ISSUE TITLE
On User Page, Add "Membership Type" dropdown

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#255]
When on a `/users/<#>/edit` page, beneath "Role", add a new dropdown selection with the user's currently assigned `membership_type` (@pollygee - did I word this in a helpful way?).

The header for this should be **"Membership Type**

The dropdown list should populate all membership types that can be selected in `/membership_types` and allow the Volunteer/Admin to select any single option.

![image](https://user-images.githubusercontent.com/47750744/72228650-9460b400-3576-11ea-9c2f-287617186384.png)

**Comment by mark100net** [comment]
I suggest `membership_types` be added to the seeds. In the seeds for `agreements` there is some suggestion as to what the values might be.

**Comment by pollygee** [comment]
Good point @mark100net

**Comment by pollygee** [comment]
I did this as part of displaying it on the dropdown for checkout.  I haven't done anything with the seeds though, I'll try to add that too as part of this.
