### ISSUE TITLE
On Users List & User's Page, add a new column "Renewal Status"

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#257]
- On `users`, add a column after `Status` titled `Renewal Status` 
- The two options should be `Current` and `Not Current`
- This status should be based on the calculated "Effective Date" in #256 and change to "Not Current" after the Effective Date has passed. 

![image](https://user-images.githubusercontent.com/47750744/72228972-3d101300-3579-11ea-9861-716870ed7cf7.png)

**Comment by mark100net** [comment]
I suggest we show status as a calculated field based on an expiration date. Please see comment on #256 for more info.

**Comment by pollygee** [comment]
👍

**Comment by abronkema** [comment]
@pollygee @mark100net - updated!

**Comment by mark100net** [comment]
This is being handled elsewhere.
