### ISSUE TITLE
On Carriers Page, Support Filtering By Overdue

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#258]
- On `/carriers`, in the Filter area, add another checkbox/toggle to allow filtering of `Overdue` carriers
- This state should also be indicated in the `State` column (@pollygee does this need to be a separate issue?) where any carrier that is checked out in an overdue loan would say "Overdue" (but still be unavailable for checkout).

![image](https://user-images.githubusercontent.com/47750744/72229107-f5d65200-3579-11ea-809c-2b67165a0b12.png)

**Comment by sarslanoglu** [comment]
@pollygee @abronkema I can work on this one

**Comment by pollygee** [comment]
@sarslanoglu that's great!!  Thanks so much.

**Comment by pollygee** [comment]
@abronkema can we please get the state put in a different ticket?
