### ISSUE TITLE
In Checkout Modal, Indicate Selected User's Membership Type

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#260]
- When selecting `Checkout` on `/carriers/<#>` and viewing the checkout modal, the User dropdown should indicate the user's First and Last name, as well as their Membership type.

![image](https://user-images.githubusercontent.com/47750744/73363199-433f0880-4276-11ea-8a47-92dc96950988.png)

**Comment by mark100net** [comment]
@abronkema I would suggest appending the membership type to each member's name in the drop down.  This would be more concise and technically less complicated (to display it separately we would probably have to create and call an new endpoint just to get this info whenever a user was selected.

For this purpose (and possibly others) we should probably add a `short_name` or `abbreviation` field to the membership types and use that here.

**Comment by pollygee** [comment]
I like that @mark100net sounds good.  You ok with that @abronkema?

**Comment by abronkema** [comment]
@mark100net @pollygee - Yep! That sounds good to me! I'll update the issue now.

**Comment by mark100net** [comment]
This is being handled elsewhere.
