### ISSUE TITLE
Limit carrier checkouts by membership type

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#283]
Membership types have a `number_of_items`.  This is the max number of carriers the member can have checked out at any time.  

If a member already has the maxium numbers of carriers allowed for their membership type, or the membership is `expired` then we want to exclude their names from the dropdown of user names in the checkout modal.

**Comment by mark100net** [comment]
Any error would only come up if they go to the checkout dialog (from carriers) and they select a member who cannot checkout any more. At least I believe that is the only way currently.

One way to prevent this (in addition to back-end checking) would be to exclude such members from the drop down.

**Comment by pollygee** [comment]
Yes I think that's correct.  I think that's good.  I'll edit the issue to reflect that solution.  Thanks.
