### ISSUE TITLE
Add Filters to Users Index page

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#284]
We have filters elsewhere in the app.  So we would like to use filterific and have a similar implementation and feel to /carriers.

We want to be able to filter by "Join Date".  So I might want to see who has joined since the beginning of the month, that type of thing.  We should be able to type in a date or select a date from a dropdown.

Other fields we want to filter by:
  -  Status
  -  Role
  -  Membership

**Comment by mark100net** [comment]
We do not have a membership index. Do you mean the users index?

**Comment by pollygee** [comment]
Yes!  Thanks, I'll edit.
