### ISSUE TITLE
Add padding to the bottom of tables on index pages

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#286]
Add a small amount of padding after the tables on the index pages.  On pages with only a few entries it doesn't matter.  But when we have a table that reaches the bottom of the page the bottom of the table and the bottom of the page are together and we want a small gap between the bottom of the table and the bottom of the page.

![Babywearing_and_Opening_print](https://user-images.githubusercontent.com/10904005/77228429-cd606a80-6b5d-11ea-93fe-e1cec0655824.jpg)

**Comment by mark100net** [comment]
This is a function of screen resolution, height of table and height of individual's browser window. I'm not sure what this accomplishes other than adding unnecessary scrollbars in a limited number of cases. Unless I'm misunderstanding something.

**Comment by pollygee** [comment]
It's just on the pages where the table takes up the whole page or runs onto other pages.  There is no bottom of the table, it looks terrible.  I Just thought it would be nice to have a tiny bit of room at the bottom of the table before the bottom of the page so:

![Babywearing_and_Inbox_—_Personal_Email__873_messages__369_unread_](https://user-images.githubusercontent.com/10904005/77239694-19d69500-6bb4-11ea-9bcf-67aaeceb0919.jpg)

instead of 
![Babywearing_and_Inbox_—_Personal_Email__873_messages__369_unread_](https://user-images.githubusercontent.com/10904005/77239707-31ae1900-6bb4-11ea-959a-947599389dce.jpg)

But if you don't want me to do that, it's ok.

**Comment by mark100net** [comment]
So I guess you are referring to after you scroll to the bottom.

**Comment by pollygee** [comment]
Right, sorry I thought that was implied with the part about the table reaching the bottom of the page.  So if the table is long enough to reach the bottom of the page, when you scroll to the bottom of the page there is no difference between the bottom of the page and the bottom of the table.  I just think there should be a little bit of space.

**Comment by pollygee** [comment]
This is resolved by the PR.
