### ISSUE TITLE
Change the banner/links menu

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#288]
We can make some improvements to our banner/links. This is what we currently have with a navbar and links on the left side taking up a lot of room:
![Babywearing](https://user-images.githubusercontent.com/10904005/77230786-2388da00-6b6d-11ea-8bdd-65bcb4e01b77.jpg)

The designer had the following design for our banner

![BW-_INVENTORY_svg](https://user-images.githubusercontent.com/10904005/77230484-f0dde200-6b6a-11ea-8797-332e2b6215b8.jpg)

We can do a few things to get closer to this beautiful design.

1. Remove the links from the left side of the page
2.  Add img_placeholder.svg (from assets) to the navbar and link to the Loans index page.
![images](https://user-images.githubusercontent.com/10904005/77230732-acebdc80-6b6c-11ea-99fd-faf3f597ffb9.jpg)

3.  Add the inventory_icon.svg (from assets) to the navbar and link to the Carriers index page.  Name on the navbar should also be carriers instead of inventory.
![BW-_INVENTORY_svg](https://user-images.githubusercontent.com/10904005/77239963-e812fd80-6bb6-11ea-80dc-99702e775a3e.jpg)

4.  Move the links (that are not a repeat of what's in the navbar) into a dropdown menu in the navbar.  These are links that would be used way less often.
      - Categories
      -  Locations
      -  Agreements 
      -  Fee Types
      -  Membership Types
5.  Change the color of the navbar icons to match the shades from the design

**Comment by pollygee** [comment]
@mark100net any comments here, do you want to edit/change anything for this?  

@ludamillion I hope you're well!  You may still be busy I'm sure, but if you had any time to look at this we'd love your input!

**Comment by mark100net** [comment]
Seems like you don't have a link to the carriers index in that scenario.

When they want to issue a carrier aren't they going to want to go to the carriers index, search for one, then make a loan? Are they going to go to the Loans listing that often?

I think if you add Loans to your list in 3. and use Carriers for the image you posted that might work.

**Comment by mark100net** [comment]
Also this issue should provide information about what is visible under what role and login status.

**Comment by pollygee** [comment]
The carriers page will be the most used I believe.  It's the home route, and the logo in the corner is a link to it as well, but we can also add a logo for it.  I think this is the logo you took out....it was named "inventory" but I think we should  put it back and call it "carriers".  Its shown in the banner from the designer.

Have permissions not been handled in previous issues?  You mean for a check of those permissions?

**Comment by mark100net** [comment]
I mean if we are reorganizing all the menus we should be clear about who can do and see what.
