### ISSUE TITLE
Update Status for Users

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#289]
We currently have `deactivated_at` on the User.  This populates the "status" column on Users index and show page.  

We also have `expiration` on the membership.  I think we don't need the `deactivated_at` anymore and the status should be populated based on `membership.expired?`.  We can then delete the `deactivated` at along with the `activate/deactivate` link on a user.

**Comment by mark100net** [comment]
It really depends on the needs. What if they want to lock someone out for some reason (or for some limited period of time) but don't want to have to mess with their memberships?

With respect to the endpoint, that we shouldn't need. If we need to keep the `deactivated_at` (or just a `deactivated` boolean) we could manipulate that in `user.update`.

**Comment by pollygee** [comment]
This has been resolved with another issue.
