### ISSUE TITLE
Link to membership agreements on member page

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#300]
The "Carriers" icon shows up for members, and since that's their only page they can use, we want to remove the icon for members and only show it when you're logged in as a volunteer/admin.

Then we want to add the membership agreements link to the profile dropdown.

![Babywearing](https://user-images.githubusercontent.com/10904005/78946961-14bd8500-7a92-11ea-8bc4-e76efe3dd9d4.jpg)

**Comment by ludamillion** [comment]
Currently due to the `menu_policy` the Carriers icon/link does not appear for members. This is current behavior. Which leaves us with the membership agreement link.

For the membership agreement link what link exactly are we talking about? Is there a way of ensuring that there is a membership agreement for a given organization? 

I don't have the domain knowledge but it seems like if organizations commonly have membership agreements than perhaps the _type_ of agreement should be codified. It would be handy to be able to link to a membership agreement via something like `ActsAsTenant.current_tenant.membership_agreement`

**Comment by pollygee** [comment]
Hiiiiiii!!   How are you?  We've missed you, So good to see you :)

You're right the carriers icon was removed, maybe it got scooped up with some other work.

In taking another look, I see there's lots of missing info here, I'm so sorry!

Each organization creates their own membership agreements.  They can add/edit them, although we are told that they change them very rarely.  (So we will figure out how to handle the change to membership agreements at a later point).  When Logged in as an admin you can see and edit the agreements
![Babywearing](https://user-images.githubusercontent.com/10904005/81926044-62f10700-95af-11ea-9810-88d5af430b94.jpg)

When you select an agreement you get the options to Sign or Edit them.
![Babywearing](https://user-images.githubusercontent.com/10904005/81926152-8916a700-95af-11ea-8c01-63f9329c8d4f.jpg)

Right now a member doesn't have access to this page.  I think we want them to have access to this page, but only allow the Sign option for them.  

I think we have an Icon we aren't using, it's like a gear setting.  Maybe we could use this icon for membership agreements to have a shortcut in the banner.  But I defer to you on this, you def know better than I what would be best!

Let me know if I'm still missing anything.

**Comment by ludamillion** [comment]
Just a quick loopback. I'm still working on this. Not a ton of bandwidth these days between the new baby, work, and life during quarantine.

My approach so far is to allow agreements to have a `kind` attribute which is currently 'membership' or 'other'. Regular members than can only see membership agreements and can only sign them (i.e. not edit them). Seems to achieve the desired result.

**Comment by pollygee** [comment]
I totally understand that!  Working with a toddler at home and that's keeping me super busy too!

I would have though that we could just let members have access to this same page we see now and just hide the `Edit` and `Destroy` buttons.  When a member just sees the two links they can click on each link and then "agree" to them.  But I could be missing something.  I think we disallowed this whole page because we didn't want users to be able to edit or destroy them.  But they do need to be able to click on the links.

I'm not sure that we will ever have another `kind` of agreement.  I think we only have `membership` type agreements.  

Maybe I'm missing something though, @mark100net do you have anything to add to this conservation?

**Comment by mark100net** [comment]
@pollygee @ludamillion Yungchih and I are going to work on this tomorrow so @ludamillion if you want to PR if not ready for that just let us take over your branch so far that would be fine, thanks.

**Comment by ludamillion** [comment]
I’ll push up what I have tonight. It sounds like it was overkill but some of it should be useful

**Comment by pollygee** [comment]
Thanks @ludamillion!  I spoke with Mark this afternoon.  I think this issue is one of our last pieces that we really need to get in order before we  can hand this over to MAB and let them start using it to see how we're doing.  Other stuff is kind of "nice to have" but without this they can't really do much.
We do have other stuff if you find a little time to pitch in.  We'll also be adding other organizations and features at some point, to start expanding so there will always be work to do.  Stay well and we hope to have your help again soon!

**Comment by ludamillion** [comment]
So it looks like what I had done so far (minus the over engineered `kind` code) actually does do what we want it too. Or at least provides a good start. So I did open up a PR for it here https://github.com/rubyforgood/babywearing/pull/341

It's always good to actually have a project in front of it's intended users. I hope to be able to contribute some more.
