### ISSUE TITLE
Default date to today in Checkin modal

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#317]
Carriers mostly get returned at meetings.  Volunteers will almost always be using the current date for returns, so defaulting to the current date will be helpful to them.

**Comment by cato-hga** [comment]
👋  I can work on this one.

**Comment by pollygee** [comment]
Thanks @cato-hga

**Comment by mark100net** [comment]
@cato-hga I have some time today so I will take this one over thanks.
