### ISSUE TITLE
Add validations for the create an account page

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#318]
The fields on the sign up page don't have any format validations.  

To help make sure we don't have typos we can add format validations to:
Email
Postal Code
Phone number

**Comment by cato-hga** [comment]
👋  I can work on this issue.

**Comment by pollygee** [comment]
@cato-hga awesome thanks!!

**Comment by cato-hga** [comment]
👋 Quick question.. For the phone number format, should I keep the default formate to an 11(1-813-843-2213) or a 10 digit(813-843-2213) number?
