### ISSUE TITLE
Pretty up the Quick Links menu

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#319]
The quick links area needs some styling.

![Babywearing_and_Mosaic_Basket_Tutorial_-_YouTube](https://user-images.githubusercontent.com/10904005/82213546-512a9f00-98e2-11ea-9eed-2869ac2867f7.jpg)

**Comment by pollygee** [comment]
@ludamillion do you have any suggestions here for this?

**Comment by ludamillion** [comment]
Sure thing. I'll look at it in more detail but I expect just some better spacing would be enough.

**Comment by ludamillion** [comment]
If we properly apply the Bootstrap structuring/styling we get this. Personally I think this is fine. As long as we're using Bootstrap we might as well take advantage of it.

<img width="826" alt="Screen Shot 2020-05-19 at 11 33 15 PM" src="https://user-images.githubusercontent.com/1638226/82401992-4c243780-9a29-11ea-966d-42714b9540e1.png">

**Comment by pollygee** [comment]
Sorry I missed this!  Sounds good to me @ludamillion  thanks.
