### ISSUE TITLE
Admin can change the wording in an email as well as the timing of these emails

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#364]
We want an admin of the group to be able to create the wording of emails they would like to send.

We should probably have options of when these emails would get sent.  Some times when we might be able to want to send emails would include
  -  when a member joins
  -  when a carrier is checked out
  - 1 week or 1 day before a carrier is due
  - 1 week or 1 day after a carrier has past it due dates

Need some more details around what this would look like.

**Comment by mark100net** [comment]
For the frequency question on reminder emails, we can possibly add a few fields (three?) to the organization that would allow them to specify when emails are sent. Something like (with possible values):
    
    reminder_1: -7
    reminder_2: -1
    reminder_3: 1

In this example, the job would run once per day, and it would send out a reminder email to everyone with a carrier due in 7 days, in 1 day and 1 day overdue.

If they want less than three, they can leave the field(s) blank(nil).

I'm not sure how (or whether) they would want to handle sending multiples after an item is overdue.
