### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#47]
- Add logo to top
- style log in form
- style registration form
- top navbar

**Comment by cattywampus** [comment]
Hi @NiquiCara! I was wondering if you had time to work on this issue? I'd be happy to pair with you remotely if you're interested.

**Comment by NiquiCara** [comment]
I haven't, and would greatly appreciate the opportunity to pair.

**Comment by abronkema** [comment]
Hey @NiquiCara - I can post in the Ruby for Good general and try to coordinate some pairing time. Is there anything in particular you're struggling with so I can try to prep anyone who's available?

**Comment by ludamillion** [comment]
I'd be happy to work on this one.

**Comment by abronkema** [comment]
@ludamillion - thanks! Assigned to you. Please let me know if you have any questions.

**Comment by ludamillion** [comment]
@abronkema Will do. I asked on the Slack channel but I'll ask here too. Is there any kind of design document or wireframes for this? I'd be happy to just use my own design sense but wouldn't want to be going in the wrong direction if there is one.
