### ISSUE TITLE
Send Transaction Confirmation Email on Submit

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#48]
Once a transaction has been completed, send user an email noting the following:

-------
`Greeting`: Hello <name>,
`Subject`: Transaction receipt from MidAtlantic Babywearing
`Body`:

Check out these pointers...
https://www.youtube.com/watch?v=rfJvWBh7KPw
https://midatlanticbabywearing.org/babywearing-safety/
https://docs.google.com/document/d/1AxWPN7ACTVN76glH8wAllX5ggs2HwC0cwgBshJz_tnQ/edit?usp=sharing

You can also get a fit check on our facebook group.

Please keep the following for your records:
- `Item Information`
- Check-Out Date
- `Check-In Due Date`
- `Location`

Thank you for using MidAtlantic Babywearing.

**Comment by pollygee** [comment]
@abronkema how is this different from #168 ?

**Comment by abronkema** [comment]
@pollygee - it isn't! closing :)
