### ISSUE TITLE
Landing page should display browsable inventory

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#63]
The default landing page should display the following, based on authentication/organization:

- If user is authenticated and assigned to an organization, show that organization's inventory page. 
- If user is not authenticated or not assigned to an organization, show a link to sign up for an organization (at this time it would only be MidAtlantic Babywearing but would expand to show other organizations at scale)

**Comment by kaziski** [comment]
On the last day of R4G, @cattywampus verbally assigned me to put a sidebar on all pages and render index page as the main content when a link on the sidebar is clicked. I'm working on it and figured I'd work on this at the same time since it requires doing a similar thing.

**Comment by abronkema** [comment]
Sounds good @codingmamakaz! Thanks

**Comment by kaziski** [comment]
Does the browsable inventory belong to a specific organization? Won't there be more than one organization?  If so, how do we know which inventory to show to unauthenticated users? Can a user belong to only one organization?

I created the sidebar. I wasn't clear on how inventories are set up, so I pushed PR for the sidebar and working on this separately.

**Comment by abronkema** [comment]
Yep! The browsable inventory belongs to an organization, and within that
organization there might be items at different locations, but they should
be viewable.

**Comment by kaziski** [comment]
Ok, I’m sorry with all the questions. I’m a little confused.
Before a user logs in, should the page show the inventory of MidAtlantic Babywearing? or the page with a list of organizations they can click to view their inventories? 
As for authenticated users, it doesn’t seem there are any associations between organization model and user model yet. Would the associations be User belongs to Organization and Organization has many Users? 
Also, it this an appropriate place to ask questions like this or should I be asking on Slack?

**Comment by abronkema** [comment]
No apologies needed! Thanks for the excellent follow-through and thoughtfulness. 
1 - We haven't talked through the multi-tenant model (where there would be multiple organizations). I'll leave it up to @cattywampus but my thought is, for now, default to MAB's organization.
2 - You're correct - a user would belong to an organization (in this case, MAB). If the user is authenticated, they should see their organization's inventory page by default.
3 - Absolutely fine to leave clarifying questions here if that works for you. You may get a quicker response to more technical questions in Slack, though.

**Comment by pollygee** [comment]
@codingmamakaz are you still working on this?

**Comment by kaziski** [comment]
@pollygee, I'd love to, but I've been very busy trying to finish my school. If anyone is interested in taking over, they should!

**Comment by pollygee** [comment]
@codingmamakaz Yeah I totally get it!  We have a bunch of people coming in to help out, and we'll get some more from Hacktoberfest.  This is a high priority, so I'm going to take you off the issue in the hopes that we can get someone to pick it up.  We're trying to get to MVP as soon as possible so we can deploy and have something working for MAB.  We hope to see you back when you're finished with school - there will still be plenty to do!

**Comment by kaziski** [comment]
Sounds good! Yes, I'm definitely planning on coming back to work on more stuff when I finish my final project :)

**Comment by LizPrescott** [comment]
I can do this.

**Comment by LizPrescott** [comment]
Oh yep. I see the source of confusion here. When I, a user, first sign up for an account, I don't have an organization yet.....

**Comment by LizPrescott** [comment]
Submitting a pr to add organization_id to the user table.

**Comment by abronkema** [comment]
@LizPrescott did you want to take the remainder of the issue? If so, I'm happy to assign it to you!

**Comment by LizPrescott** [comment]
Sure!

**Comment by abronkema** [comment]
@LizPrescott - I've updated the issue a bit to clarify the organization concern. Please let me know if you have any concerns with the change.

**Comment by LizPrescott** [comment]
@abrankema Responding to @pollygee comment on pr #76 . See prs #96 and #97
This approach lets us leave the whole organizations question out of this issue.
