### ISSUE TITLE
Item images in browsable inventory should be the same size

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#64]
See #59 

All images (placeholder and uploaded) should be the same size.

- Each `item` (ie `/carriers/5/edit) has a photo upload option that is used for that specific item.

**Comment by digilou** [comment]
@abronkema @pollygee Mind if I take a look at this to see if I can contribute?

**Comment by pollygee** [comment]
That would be great, thanks!  Let me know if you run into any problems.  Feel free to join our slack channel as well if you want to chat to others who work on the project or just join our community!

**Comment by digilou** [comment]
@pollygee I think the Slack channel sounds like a great idea. I have questions already! Where do I join?

**Comment by pollygee** [comment]
Our website - https://rubyforgood.org/ there's a link for slack invite at the top of the page - the #.  You can sign up there and then join the #babywearing channel.

**Comment by pollygee** [comment]
@abronkema I think this has been resolved, correct?  Can we close this issue?

**Comment by abronkema** [comment]
resolved via #150
