### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#70]
**Describe the bug**
We have a failing test.  

**To Reproduce**
Run the test in the file
`# ./spec/features/user_spec.rb:58:in`

**Expected behavior**
Seems we would expect to only get one email from `Devise` but we're getting two
`Expect(Devise.mailer.deliveries.count).to eq 1`  but we got 2

**Comment by schattian** [comment]
I'm on it.

**Comment by pollygee** [comment]
Great thanks!!  I'll assign it to you so that nobody else picks it up.

**Comment by schattian** [comment]
Well, currently I'm in trouble trying to run tests at local.
Executed: 
`docker exec -it babywearing_db_1 psql -c 'create database babyweraing_test;' -h localhost -U postgres`

but getting: 
`psql: FATAL:  role "postgres" does not exist`

You are following chained different steps to set up the test env?

**Comment by pollygee** [comment]
I just submitted a PR with an update to the README with what I had to do to get it running locally just so there would be something there - maybe it will need updating.  I had to run:
`rails db:setup`
`rake db:migrate`

and you ran `bundle` first right? That's all I had to do.

**Comment by schattian** [comment]
> I just submitted a PR with an update to the README with what I had to do to get it running locally just so there would be something there - maybe it will need updating. I had to run:
> `rails db:setup`
> `rake db:migrate`
> 
> and you ran `bundle` first right? That's all I had to do.

Oh, sorry, my fault. Trying to create the db through the container instead from rake.
