### ISSUE TITLE
Seed data is breaking several show pages for a carrier

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#75]
**Describe the bug**
When navigating to certain show pages for carriers in the seed data, the page is broken and gives an error ` MiniMagick::Invalid in Carriers#show `

**To Reproduce**
Go to `/carriers/6` or `/carriers/19`

**Expected behavior**
We should see the information about the carrier corresponding to the seed data information.
I'm not sure why these couple pages are broken and the other ones seem to work fine.

There is a csv file used, maybe there's something in there that is causing a problem?

From the 3000/carriers page, it is the link for `Bitty Bean Baby` and `Lillebaby All Seasons` that are broken.

**Comment by moriie** [comment]
Hi, I'm unable to reproduce the issue. :(
Both pages work for me - /carriers/6 as reference. 

![work](https://user-images.githubusercontent.com/46545695/66109715-47db0500-e593-11e9-9e4e-1d0631863050.jpg)

**Comment by pollygee** [comment]
Oh great!  Thanks so much.  I see that there is a photo on that page.  I didn't see any photos on other pages so maybe there's something I don't have installed to make that work.  Do you know what you have installed to make it work?  I can add it to the setup instructions if I can figure out what it is.

**Comment by pollygee** [comment]
I figured it out!  I needed to install imagemagic with brew install imagemagick which broke lots of things but once I got things fixed it's working now.  I'll add to the setup instructions.  Thanks!
