### ISSUE TITLE
User registration form: required fields aren't indicated

### ISSUE THREAD

**Issue by digilou** [rubyforgood/babywearing#78]
**Describe the bug**
When signing up for the first time, I had not visual indication that all fields were required until I received a list of errors after clicking "Sign up". Visual users, as well as screen reader users are given no heads up that they need to fill it all in, even though we assume it makes sense.

**To Reproduce**
1. Go to Sign Up page.
2. Partially fill out form.
4. See error.

**Expected behavior**
With no indication as to what's required or optional, I think most of these fields are optional, with the exception of the email and password fields.

If required, a screen reader user will expect to hear their screen reader announce "field required". A visual user will expect to see "*", "(required)", or "(optional)" written next to the label.

**Screenshots**
<img width="962" alt="Screen Shot 2019-10-05 at 4 37 15 PM" src="https://user-images.githubusercontent.com/8865558/66262520-87ba0c00-e78e-11e9-9406-d5b91115fb92.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Version: 69

**Additional context**
This is an accessibility and usability issue. Screen reader users are not warned with a `required` or `aria-required` attribute. Visual users with cognitive disabilities as well as people without may become frustrated when it doesn't work for them the first time, and they're presented with a list of errors at the top.

**Comment by pollygee** [comment]
Thank you @digilou!

**Comment by enderahmetyurt** [comment]
@pollygee could you assign this issue to me?

**Comment by pollygee** [comment]
Done!! Thanks so much!
