### ISSUE TITLE
List carriers by category in /categories

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#86]
When accessing `/categories`, each different carrier category has an option to "Show". 

When clicking that link and accessing that category, all carriers assigned to that category should be displayed. 

Example, when on `/categories` and clicking Show for `Ring Slings`, I'm taken to `/categories/18`, but nothing other than the category name are displayed. Instead, this should show me all carriers that are assigned to the category of `Ring Sling`.

**Comment by Drew-Goddyn** [comment]
@abronkema I'll give this is a shot if you can assign me, thanks :)

**Comment by mauricio-prl** [comment]
@Drew-Goddyn I'm about to push a PR to this because I was working on this earlier this morning...

**Comment by Drew-Goddyn** [comment]
🤷‍♂

**Comment by pollygee** [comment]
@m-pereira thanks so much for the hard work!  We'll get someone to review your PR soon!  In the future please comment on an Issue so we can assign it so others know you're working on it.  Thanks so much!

@Drew-Goddyn so sorry about that!  We have LOTS more work so maybe you see another issue?  We'll be putting in a bunch more soon too!  Thanks for coming to help!  We're so grateful.

**Comment by mauricio-prl** [comment]
@pollygee and @Drew-Goddyn, I'm sorry about that. It's my first time contributing with opensource projects. Next time I will comment something before start working in the issue

**Comment by pollygee** [comment]
@m-pereira no problem!!  So exciting it's your first contribution!  Congratulations and thanks for picking us to help.  We have plenty of things we need help with so there's enough to go around!
