### ISSUE TITLE
Don't show sign up / sign in flash messages twice

### ISSUE THREAD

**Issue by DamirSvrtan** [rubyforgood/babywearing#90]
**Describe the bug**
Currently when a user signs up or signs it, the flash message is shown twice. I think both of the issues can be resolved with one solution, seems they are related.

**To Reproduce**
If I click on the "Sign Up" button when i'm logged in, I get shown this message twice: "You are already signed up".

If I click on a navigation button while logged out, I am shown "You need to sign in or sign up before continuing" twice as well.

**Expected behavior**
The expected behavior would be for those messages to be shown once, not twice

**Screenshots**
<img width="925" alt="Screen Shot 2019-10-09 at 9 23 04 AM" src="https://user-images.githubusercontent.com/1437202/66500516-8599cb00-ea76-11e9-97d8-21d8ad8bbf04.png">
<img width="860" alt="Screen Shot 2019-10-09 at 9 22 50 AM" src="https://user-images.githubusercontent.com/1437202/66500517-86326180-ea76-11e9-9b8c-4eb08b2df6ce.png">

**Comment by JuarezLustosa** [comment]
Can I help with this ?

**Comment by DamirSvrtan** [comment]
Sure thing, go for it!
