### ISSUE TITLE
Change from fixtures to factory_bot

### ISSUE THREAD

**Issue by mauricio-prl** [rubyforgood/babywearing#91]
I propose to change the fixtures for [factory bot](https://github.com/thoughtbot/factory_bot_rails). WDYT?

**Comment by DamirSvrtan** [comment]
Thumbs up from me!

**Comment by pollygee** [comment]
Hi @m-pereira thanks so much for the suggestion.  I think fixtures are working for us for now and we have a lot of development to do to get us to MVP, so we'll stick with what we've got for now!  Thanks for helping us at Ruby For Good!  We have lots of other work to do, so I hope you'll stick around and give us a hand getting to deployment!!
